### ISSUE TITLE
vulnerability issues with jszip

### ISSUE THREAD

**Issue by dklbe** [ffflorian/jszip-cli#836]
Hi,

your current release (3.1.0) references jszip 3.2.2 which is having vulnerability issues. I saw that in your current master branch you already switched to jszip 3.7.1. Is this going to be released any time soon?

Cheers

Daniel

**Comment by ffflorian** [comment]
Hi @dklbe, thanks for the reminder. I just released [version 3.1.1](https://github.com/ffflorian/jszip-cli/releases/tag/v3.1.1).

**Comment by ffflorian** [comment]
@dklbe which Node.js version are you using?

**Comment by dklbe** [comment]
@ffflorian 14.17.1

**Comment by dklbe** [comment]
@ffflobot @ffflorian   Could you reproduce the error on your side?

**Comment by ffflorian** [comment]
@dklbe Yes, sorry for the delay. I will fix it as soon as I have time for it.

**Comment by ffflorian** [comment]
@dklbe Should be fixed with version [3.1.3](https://github.com/ffflorian/jszip-cli/releases/tag/v3.1.3).

**Comment by dklbe** [comment]
@ffflorian The problem is still there. I tested also on our build runner (node v14.17.4) and locally with node v16.8.0.

**Comment by ffflorian** [comment]
@dklbe Weird. Can you give me an example of how you are using jszip-cli? Are you using it with a config file? And with which settings?

**Comment by dklbe** [comment]
@ffflorian   I added those minimal example:  https://github.com/dklbe/test/ -> npm install -> npm run-script build  Works with version 3.0.2  but not with the 3.1.3

**Comment by ffflorian** [comment]
Thanks for the example! I was running into this issue: https://github.com/tj/commander.js/issues/1442
Your problem should finally be fixed with version [3.1.4](https://github.com/ffflorian/jszip-cli/releases/tag/v3.1.4).

**Comment by dklbe** [comment]
@ffflorian  Thanks for the fix, but I'm running in a new issue.  If I run jszip with no command line params I get "Error: No configuration file and no mode specified." even though the .jsziprc.json is in the same folder. If I specify the path to the config file then I get:   "Error: entry.replaceAll is not a function"

**Comment by ffflorian** [comment]
@dklbe Can you try with version [3.1.5](https://github.com/ffflorian/jszip-cli/releases/tag/v3.1.5)?

**Comment by dklbe** [comment]
@ffflorian No, I ran into the same problem. I switched to another zipping library in the meantime. Thanks again for your effort.

**Comment by ffflorian** [comment]
Alright, fair enough :slightly_smiling_face:
